// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Flatbuffer
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Packet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static Packet GetRootAsPacket(ByteBuffer _bb) { return GetRootAsPacket(_bb, new Packet()); }
  public static Packet GetRootAsPacket(ByteBuffer _bb, Packet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Packet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Flatbuffer.PacketContent ContentType { get { int o = __p.__offset(4); return o != 0 ? (Flatbuffer.PacketContent)__p.bb.Get(o + __p.bb_pos) : Flatbuffer.PacketContent.NONE; } }
  public TTable? Content<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Flatbuffer.S_Test ContentAsS_Test() { return Content<Flatbuffer.S_Test>().Value; }
  public Flatbuffer.S_Test2 ContentAsS_Test2() { return Content<Flatbuffer.S_Test2>().Value; }

  public static Offset<Flatbuffer.Packet> CreatePacket(FlatBufferBuilder builder,
      Flatbuffer.PacketContent content_type = Flatbuffer.PacketContent.NONE,
      int contentOffset = 0) {
    builder.StartTable(2);
    Packet.AddContent(builder, contentOffset);
    Packet.AddContentType(builder, content_type);
    return Packet.EndPacket(builder);
  }

  public static void StartPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddContentType(FlatBufferBuilder builder, Flatbuffer.PacketContent contentType) { builder.AddByte(0, (byte)contentType, 0); }
  public static void AddContent(FlatBufferBuilder builder, int contentOffset) { builder.AddOffset(1, contentOffset, 0); }
  public static Offset<Flatbuffer.Packet> EndPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Flatbuffer.Packet>(o);
  }
  public static void FinishPacketBuffer(FlatBufferBuilder builder, Offset<Flatbuffer.Packet> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPacketBuffer(FlatBufferBuilder builder, Offset<Flatbuffer.Packet> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
