// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Flatbuffer
{

public enum PacketContent : byte
{
  NONE = 0,
  S_Test = 1,
  S_Test2 = 2,
};


}
